fix: update README.md
IBM/platform-services-node-sdk pull request #121
Opened 2021-07-21 17:47 UTC by Andras-Csanyi

## PR summary
Info about package deprecation

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2021-07-21 18:04 UTC, padamstx requested changes
I suggested a few changes.  I'd also like to get @dpopp07 eyes on this PR as well.

2021-07-21 18:04 UTC, padamstx commented on README.md
> +// prior to package deprecation
```suggestion
// A 'require' statement that reflects the old package name:
```

2021-07-21 18:04 UTC, padamstx commented on README.md
> +// with the new package
```suggestion
// Modify this to reflect the new package name:
```

2021-07-21 21:01 UTC, padamstx approved these changes
LGTM

2021-07-21 21:10 UTC, dpopp07 approved these changes
Looks good! 👍

2021-07-22 08:06 UTC, merged

2021-07-29 08:00 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.19.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ibm-cloud/platform-services/v/0.19.4)
- [GitHub release](https://github.com/IBM/platform-services-node-sdk/releases/tag/v0.19.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: