add list rule with service_group_id test
IBM/platform-services-node-sdk pull request #168
Opened 2022-10-12 19:03 UTC by cam-d12

Signed-off-by: Cameron Davis <cjdavis@ibm.com>

## PR summary

This PR adds CBR support for the new service_group_id parameter in rules.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

No current behavior should be modified. Adds the further control to be able to apply rules to service groups

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

2022-10-12 19:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/platform-services-node-sdk?pullRequest=168) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/platform-services-node-sdk?pullRequest=168) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/platform-services-node-sdk?pullRequest=168) it.</sub>

2022-10-12 19:51 UTC, soohoowoohoo requested changes

2022-10-12 19:51 UTC, soohoowoohoo commented on test/integration/context-based-restrictions.v1.test.js
> +const ContextBasedRestrictionsV1 = require('@ibm-cloud/platform-services/context-based-restrictions/v1');
@cam-d12 did you make this change or the generator code? The dist folder should have the latest locally built code. If you need to help with how to build the code into the dist folder, try the readme or reach out and I can try to help.

2022-10-12 19:51 UTC, soohoowoohoo commented on test/integration/context-based-restrictions.v1.test.js
> +    expect(listRes.result).toBeDefined();
I think we'll want to assert that only the 1 service group rule was returned.

2022-10-12 19:51 UTC, soohoowoohoo commented on test/integration/context-based-restrictions.v1.test.js
> +    const listParams = {
I would expect that we'd want to pass the serviceGroupId parameter to make sure filtering by the property is working as expected?

2022-10-14 19:43 UTC, soohoowoohoo reviewed
LGTM

2022-10-14 22:04 UTC, padamstx approved these changes
LGTM

2022-10-14 22:09 UTC, merged

2022-10-14 22:11 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.26.1 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/IBM/platform-services-node-sdk/releases/tag/v0.26.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: