feat(User Management): support include_settings and substring se…
IBM/platform-services-node-sdk pull request #205
Opened 2023-04-25 20:28 UTC by PureMathematics

## PR summary

Update Include_settings and substring search functionality (User Management) 

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information
the current issue for updating SDK https://github.ibm.com/IAM/uum/issues/5882 
the previous issue for the user management code change https://github.ibm.com/IAM/uum/issues/4948

2023-04-25 20:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/platform-services-node-sdk?pullRequest=205) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/platform-services-node-sdk?pullRequest=205) before we can accept your contribution.<br/><hr/>**David-Lim0305** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/platform-services-node-sdk?pullRequest=205) it.</sub>

2023-04-26 20:59 UTC, padamstx requested changes
Change look good, but same comments as the other PRs:
1. please use the git commit "-s" option.
2. one code fragment per operation within the examples code

2023-04-26 20:59 UTC, padamstx commented on examples/user-management.v1.test.js
> +  test('listUsers request include_settings example', async () => {
same comment as in Go SDK, one code fragment per operation :)

2023-04-28 13:48 UTC, padamstx reviewed
LGTM, just have the question about URL-encoding

2023-04-28 13:48 UTC, padamstx commented on examples/user-management.v1.test.js
> +      search: 'state%3AACTIVE',
same comment about URL-encoding

2023-04-28 16:56 UTC, padamstx approved these changes
LGTM

2023-04-28 22:55 UTC, PureMathematics commented
integration test
<img width="1194" alt="node-integration" src="https://user-images.githubusercontent.com/35412774/235266662-f3c695b3-ea97-4067-9bbf-1579cf856659.png">

2023-04-28 22:55 UTC, PureMathematics commented
examples test
<img width="1209" alt="node-example" src="https://user-images.githubusercontent.com/35412774/235266693-d96356f1-aa47-4a50-9a59-dae35b440144.png">

2023-04-28 22:57 UTC, merged

2023-05-31 20:13 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.35.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/IBM/platform-services-node-sdk/releases/tag/v0.35.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: