update for operations api
IBM/platform-services-node-sdk pull request #224
Opened 2023-09-14 20:38 UTC by JonahFarc

## PR summary
Adds service group support to operations
Should replace https://github.com/IBM/platform-services-node-sdk/pull/223

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
service_name parameter can now be replaced with the service group parameter.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [X] No

2023-09-14 20:46 UTC, soohoowoohoo approved these changes
LGTM

2023-09-14 20:48 UTC, JonahFarc commented
test screenshot:
<img width="870" alt="image" src="https://github.com/IBM/platform-services-node-sdk/assets/17422133/88b620c8-706a-4bb4-b858-211ef92b0eb6">

Examples Screenshot:
<img width="796" alt="image" src="https://github.com/IBM/platform-services-node-sdk/assets/17422133/14510d29-8775-41dd-a511-450e1cdc9d62">

2023-09-15 13:47 UTC, padamstx requested changes
Need to re-gen with the same API definition file as the other languages.

2023-09-15 13:47 UTC, padamstx commented on context-based-restrictions/v1.ts
> +  static DEFAULT_SERVICE_URL: string = 'https://cbr.test.cloud.ibm.com';
You must have used the staging version of the API definition when you generated this code.  I didn't see this change in the other PRs.   Please re-gen with the same version of the API definition that you used for the other languages.

2023-09-15 14:48 UTC, padamstx approved these changes
LGTM

2023-09-15 14:55 UTC, merged

2023-09-15 14:57 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.43.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/IBM/platform-services-node-sdk/releases/tag/v0.43.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: