feat(Partner Usage Reports): add partner resource usage report service to Partner usage reports
IBM/platform-services-node-sdk pull request #242
Opened 2024-02-12 07:42 UTC by manukm-ibm

## PR summary

Adding new partner API to fetch resource usage reports.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/cosell/partner.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/2063

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2024-02-15 18:07 UTC, padamstx requested changes
Still need to do the following:
1. Add a new entry to the service table in `README.md`.
2. Update .gitignore

See instructions at https://github.com/IBM/ibm-cloud-sdk-common/blob/main/CONTRIBUTING_nodejs.md#adding-a-new-service

2024-02-16 06:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/platform-services-node-sdk?pullRequest=242) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/IBM/platform-services-node-sdk?pullRequest=242) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: benbuchanan<br/>:white_check_mark: swcolley<br/>:white_check_mark: manukm-ibm<br/>:x: semantic-release-bot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/platform-services-node-sdk?pullRequest=242) it.</sub>

2024-02-16 17:08 UTC, padamstx approved these changes
LGTM

2024-02-19 07:05 UTC, manukm-ibm commented
Duplicate of https://github.com/IBM/platform-services-node-sdk/pull/243

2024-02-19 07:05 UTC, closed without merging