fix(Resource Manager): update service after recent API changes and generate examples - DRAFT
IBM/platform-services-node-sdk pull request #84
Opened 2021-03-08 13:26 UTC by Andras-Csanyi

## PR summary
This PR updates the Resource Manager service, adds examples and move configuration values out from tests into a configuration file.

This PR is still in DRAFT.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2021-03-16 14:37 UTC, pyrooka requested changes

2021-03-16 14:37 UTC, pyrooka commented on examples/resource-manager.v2.test.js
> +const configFile = 'resource_manager_v2.env';
Just simply `resouce_manager.env`

2021-03-16 14:37 UTC, pyrooka commented on examples/resource-manager.v2.test.js
> +  const testQuotaId = config.testQuotaId;
We are using these 2 params without the test prefix in the config file.

2021-03-16 14:37 UTC, pyrooka commented on test/integration/resource-manager.v2.test.js
> +  beforeAll('should successfully complete initialization', done => {
The first argument is a callback function, not a string. Check the other integration tests (search for `beforeAll` in the project)

2021-03-16 14:37 UTC, pyrooka commented on test/integration/resource-manager.v2.test.js
> +    resourceManagerService = ResourceManagerV2.newInstance({ serviceName: 'RMGR1' });
We should use the default service name constant here.

2021-03-16 14:37 UTC, pyrooka commented on test/integration/resource-manager.v2.test.js
> +    resourceManagerUsersService = ResourceManagerV2.newInstance({ serviceName: 'RMGR2' });
Please rename the variable to `deleteResourceManagerService` and change the service name to `ALT_RESOURCE_MANAGER`.

2021-03-16 14:37 UTC, pyrooka commented on test/integration/resource-manager.v2.test.js
> +    authUrl = config.AuthUrl;
`config.authUrl`

2021-03-16 14:37 UTC, pyrooka commented on test/integration/resource-manager.v2.test.js
> +    testUserAccountId = config.testUserAccountId;
We are using these 2 config parameters without the test prefix in the env file.

2021-03-16 14:51 UTC, pyrooka requested changes

2021-03-16 14:51 UTC, pyrooka commented on examples/resource-manager.v2.test.js
> +  const resourceManagerService = ResourceManagerV2.newInstance({});
We should create another service instance for the delete operation. Let's call it `deleteResourceManagerService` and the use the service name `ALT_RESOURCE_MANAGER`.

2021-03-16 14:51 UTC, pyrooka commented on examples/resource-manager.v2.test.js
> +    resourceManagerService.deleteResourceGroup(params)
Use the newly created delete service here.

2021-03-16 21:27 UTC, padamstx requested changes
Looks good, but I suggested a few minor changes.

2021-03-16 21:27 UTC, padamstx commented on examples/resource-manager.v2.test.js
> +      accountId: userAccountId
add includeDeleted true

2021-03-17 20:39 UTC, padamstx approved these changes
LGTM

2021-03-18 14:33 UTC, merged

2021-03-18 14:36 UTC, ibm-devx-automation commented
:tada: This PR is included in version 0.17.16 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ibm-platform-services/v/0.17.16)
- [GitHub release](https://github.com/IBM/platform-services-node-sdk/releases/tag/v0.17.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: